<a href="https://colab.research.google.com/github/bchanyoo/dakum/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

In [59]:
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [60]:
data = iris.data
label = iris.target
columns = iris.feature_names

In [61]:
data = pd.DataFrame(data, columns = columns)
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [62]:
data.shape #data 150개, 특성은 4개. 

(150, 4)

In [63]:
#data 쪼개기
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, label, test_size = 0.2, random_state = 2023) # 20프로를 테스트로 사용, 2023번만큼 섞음.

In [64]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [65]:
#Training
lr.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [66]:
y_pred = lr.predict(X_test)

In [67]:
y_pred

array([2, 1, 1, 2, 1, 2, 1, 1, 0, 1, 0, 1, 0, 2, 0, 2, 0, 1, 0, 0, 1, 0,
       2, 1, 0, 0, 0, 2, 1, 0])

In [68]:
y_test

array([2, 1, 1, 2, 1, 2, 1, 1, 0, 1, 0, 1, 0, 2, 0, 2, 0, 1, 0, 0, 1, 0,
       2, 1, 0, 0, 0, 2, 1, 0])

In [69]:
# 결과확인
from sklearn.metrics import accuracy_score

In [70]:
print('로지스틱 회귀 정확도: {:.2f}'.format(accuracy_score(y_test, y_pred) * 100))      #overfitting
print('로지스틱 회귀, 계수(w): {0}\n절편(b): {1}'.format(lr.coef_, lr.intercept_))

로지스틱 회귀 정확도: 100.00
로지스틱 회귀, 계수(w): [[-0.44734561  0.8926404  -2.33623964 -1.03295779]
 [ 0.49390809 -0.33483512 -0.19125056 -0.85050783]
 [-0.04656248 -0.55780528  2.5274902   1.88346562]]
절편(b): [  9.47258972   2.14495508 -11.6175448 ]


In [71]:
# Support Vector Classification
from sklearn.svm import SVC

In [72]:
for i in [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]:
  svc = SVC(C = i) #C값은 노이즈를 몇 개까지 무시할 것인가에 대한 값.
  svc.fit(X_train, y_train)
  y_pred = svc.predict(X_test)
  print('i = {}일 때 정확도 : {:.2f}'.format(i, accuracy_score(y_test, y_pred) * 100))

i = 0.1일 때 정확도 : 90.00
i = 0.2일 때 정확도 : 100.00
i = 0.3일 때 정확도 : 100.00
i = 0.4일 때 정확도 : 100.00
i = 0.5일 때 정확도 : 100.00
i = 0.6일 때 정확도 : 100.00
i = 0.7일 때 정확도 : 100.00
i = 0.8일 때 정확도 : 100.00
i = 0.9일 때 정확도 : 100.00
i = 1일 때 정확도 : 100.00


In [73]:
#DecisionTree
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(max_depth = 3) #Route node 제외하고 3개.

In [74]:
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
print('Tree algorithm의 정확도 : {:.2f}'.format(accuracy_score(y_test, y_pred) * 100))

Tree algorithm의 정확도 : 100.00


In [75]:
from sklearn.tree import export_graphviz
export_graphviz(dt, out_file = 'tree1.dot')

In [76]:
from subprocess import call
call(['dot', '-Tpng', 'tree.dot', '-o', 'decision-tree.png', '-Gdpi = 500']) #선이 선명한 png파일로 저장. 
#dpi는 dot per inch(해상도)

2

In [77]:
#위 코드가 갑자기 2가 return되면서 오류가 발생........

#from IPython.display import Image
#Image(filename = 'decision-tree.png')

In [78]:
#RandomForest
from sklearn.ensemble import RandomForestClassifier

In [79]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
print('Random Forest Accuracy : {:.2f}'.format(accuracy_score(y_test, y_pred) * 100))

Random Forest Accuracy : 100.00


In [80]:
import os
from os.path import join

abalone_path = join('sample_data', 'abalone.txt')
column_path = join('sample_data', 'abalone_attributes.txt')

abalone_columns = list()
for l in open(column_path):
  abalone_columns.append(l.strip())

In [81]:
abalone_columns

['Sex',
 'Length',
 'Diameter',
 'Height',
 'Whole weight',
 'Shucked weight',
 'Viscera weight',
 'Shell weight',
 'Rings']

In [82]:
data = pd.read_csv(abalone_path, header = None, names = abalone_columns)
data = data[data['Sex'] !='I'] # 성별 항목에서 I가 아닌 것들만 출력 
label = data['Sex'].map(lambda x: 0 if x == 'M' else 1) #x의 기본값은 0, 만약 x가 m이면 넘어가고, m이 아니면 1
del data['Sex']
data.head()

Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   0.440     0.365   0.125        0.5160          0.2155          0.1140   
6   0.530     0.415   0.150        0.7775          0.2370          0.1415   

   Shell weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
6         0.330     20

In [83]:
#data 쪼개기
X_train, X_test, y_train, y_test = train_test_split(data, label, test_size = 0.2, random_state = 2023)

In [84]:
rf = RandomForestClassifier(max_depth = 5)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

In [85]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
print('Accuracy: {:.2f}'.format(accuracy_score(y_test, y_pred) * 100))
print('Precision: {:.2f}'.format(precision_score(y_test, y_pred) * 100))
print('Recall: {:.2f}'.format(recall_score(y_test, y_pred) * 100))
print('AUC: {:.2f}'.format(roc_auc_score(y_test, y_pred) * 100))

Accuracy: 52.56
Precision: 52.00
Recall: 23.72
AUC: 51.62


In [90]:
best_model_depth = 0
best_model_accuracy = 0

for i in [2,3,4,5,6,7,8,9,10]:
  rf = RandomForestClassifier(max_depth = i)
  rf.fit(X_train, y_train)
  y_pred = rf.predict(X_test)

  acc = accuracy_score(y_test, y_pred)

  print('Accuracy: i = {}   {:.2f}'.format(i, acc * 100))

  if best_model_accuracy < acc:
    best_model_depth = i
    best_model_accuracy = acc

print('--------------------')
print('best_model_depth : {0}, best_model_accuracy : {1}'.format(best_model_depth, best_model_accuracy))

Accuracy: i = 2   52.20
Accuracy: i = 3   51.15
Accuracy: i = 4   52.38
Accuracy: i = 5   53.44
Accuracy: i = 6   53.97
Accuracy: i = 7   54.32
Accuracy: i = 8   55.03
Accuracy: i = 9   54.85
Accuracy: i = 10   53.44
--------------------
best_model_depth : 8, best_model_accuracy : 0.5502645502645502
