<a href="https://colab.research.google.com/github/bchanyoo/dakum/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy
# c언어로 개발된) 파이썬에서 과학적 계산을 위한 핵심 라이브러리
# 다차원 배열 객체와 함께 작동하는 도구들을 제공.
# but, 고수준 데이터 분석 기능을 제공하진 X 
# Pandas와 같은 도구를 함께 사용함.

In [ ]:
import numpy as np #넘파이 배열이 생김

In [ ]:
arr = np.array([1,2,3,4]) #넘파이의 배열을 만든다.
print(arr)
print(type(arr)) #nd array, 사이즈가 큰 데이터들은 기본배열보다 넘파이배열이 장점들이 많다.

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
#zeros, ones, empty를 사용해 배열을 생성함.
car = np.zeros((3,3)) #0으로 채워진 3x3 배열이 생긴다
print(car) 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.empty((4,4)) #이전에 사용하던 찌꺼기가 남아있는 것. 그래서 0or1로 초기화를 시킬 필요가 있음.

array([[2.75720488e-316, 0.00000000e+000, 6.01346954e-154,
        5.98149672e-154],
       [4.71592575e+257, 7.20358919e+159, 1.33856858e-152,
        3.65588281e+233],
       [1.35712977e+166, 2.31633955e-152, 3.94355938e+180,
        1.89130905e+219],
       [3.68321739e+180, 5.98178806e-154, 1.06758000e+224,
        3.11079466e+161]])

In [ ]:
#특정 범위의 변수를 생성할 때 arange를 사용.
print(np.arange(10))
print(np.arange(1,10)) #1은 시작, 10은 끝나는 지점.
print(np.arange(1,10,2)) # 2씩 간격을 두기기

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [ ]:
# ndarray 배열의 모양, 차수, 데이터 타입 확인해보기.
arr = np.array([[1,2,3],[4,5,6]]) #2차원, 리스트 괄호가 두개가 열리면 2차원, 한개면 1차원, (2,3)의 배열인 것.
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr.ndim #number dimension인것 같음(차원 확인)

2

In [ ]:
#data 모양 확인하는 법.
arr.shape

(2, 3)

In [ ]:
#data 타입의 확인
print(type(arr))
print(arr.dtype) # dtype은 배열 안의 데이터타입을 확인 가능.
# int64는 64비트 정수형형이다.

<class 'numpy.ndarray'>
int64


In [ ]:
#8비트는 2의 8승, 8비트로 표현할 수 있는 숫자는 -128 ~ 0 ~ + 127까지만 표현이 가능. 130의 숫자는 표현이 불가능. 
#16비트는 2의 16승, 65536. -32768 ~ 0 ~ +32767

In [ ]:
# ndarray 배열의 타입 변환
arr_int = np.array([1,2,3,4])
print(arr_int.dtype)
arr_float = arr_int.astype(np.float64)
print(arr_float.dtype)

int64
float64


In [ ]:
#문자 배열에서 숫자 배열로 변환
arr_str = np.array(['1','2','3','4'])
print(arr_str.dtype) #U1 = unicode 1
arr_int = arr_str.astype(np.int64)
print(arr_int)
print(arr_int.dtype)

<U1
[1 2 3 4]
int64


In [ ]:
#배열의 연산 기능
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
print(arr1 + arr2) # 같은 차원의 숫자끼리 더해짐
print(arr1 - arr2)
print(arr1 * arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [ ]:
#연산자 사용
print(np.add(arr1, arr2))
print(np.multiply(arr1, arr2))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [ ]:
#ndarray 배열 슬라이싱하기
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [ ]:
arr_1 = arr[:2,1:3] #0부터 2까지니 2 부분인 [7,8,9]를 먼저 끊어냄. 두번째 1에서 3까지, 세로 슬라이싱 먼저, 그다음 가로 슬라이싱싱
print(arr_1)

[[2 3]
 [5 6]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[0,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3


In [ ]:
#배열의 일정 수 이상 값을 판별하기
arr = np.array([[1,2,3],[4,5,6]])
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]]


In [ ]:
arr[idx] #True 값만 출력됨.

array([4, 5, 6])

In [ ]:
#csv file = comma separated value = 콤마로 구분되어있는 데이터
#넘파이로 파일 불러오기
redwine = np.loadtxt(fname='winequality-red.csv', delimiter = ';', skiprows=1) 
#레드와인 변수로 저장,
#첫번째 줄은 건너뛰고, 
#파일의 형식이 콤마가 아닌 세미콜론으로 돼 있어서 구별자를 알려줘야함(delimeter)

In [ ]:
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [ ]:
# 기초통계함수 사용
# sum = 합계
# mean = 평균
# std = standard division(표준편차)
# var = 분산 (variance, std의 제곱)
# min = 최소값
# max = 최대값

In [ ]:
print(redwine.sum()) #데이터들의 합계
print(redwine.sum(axis=0)) #가로축이 0번, 세로축이 1번.
print(redwine.mean(axis=0))

152084.78194
[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]
[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [ ]:
print(redwine.mean(axis=1))
#1번축은 각 항목별 평균
#0번축은 ?

[ 6.21198333 10.25456667  8.30825    ...  8.37347833  8.76795583
  7.7077075 ]


In [ ]:
print(redwine[:,0].mean()) #축의 반대로 출력됨?? 다시 공부부

8.31963727329581


In [ ]:
print(redwine.max(axis = 0)) #와인 평가 항목별의 최댓값

[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       8.     ]


In [ ]:
print(redwine.min(axis = 0))#와인 평가 항목별의 최소값값

[4.6     0.12    0.      0.9     0.012   1.      6.      0.99007 2.74
 0.33    8.4     3.     ]
